nginformatica/flipper-ui

doczrc.js
package.json
public/index.html
src/colors.js
src/components/Advertise.js
src/components/Avatar.js
src/components/Box.js
src/components/Button.js
src/components/Card.js
src/components/Checkbox.js
src/components/Header.js
src/components/Node.js
src/components/Pagination.js
src/components/Picker.js
src/components/TextArea.js
src/components/TextField.js
src/docz/Advertise.mdx
src/docz/Box.mdx
src/docz/Button.mdx
src/docz/Checkbox.mdx
src/docz/Pagination.mdx
yarn.lock

A few adjusts in components like adding missing `;` in styled components, added font-family to not depend of the body styled.
Added two components:
* Advertise
* Box

Components

---

src/core/Button.tsx
src/docz/Button.mdx
yarn.lock

Atividade era fazer um button outlined com dashed, dashed foi feito por css por não ter dísponivel no material-ui nem constar no material design.

Outlined dashed button

---

README.md
package.json
src/core/Collapse.tsx
src/core/ExpansionPanel.tsx
src/core/ListItem.tsx
src/docz/ExpansionPanel.mdx

0.4.3 - Expansion panel with option to 'icon' position (left or right)

---

package.json
src/core/ExpansionPanel.tsx

0.4.4 - ExpansionPanel styles

---

package.json
src/core/Button.tsx
src/core/Typography.tsx
src/docz/Button.mdx
src/docz/Typography.mdx

- `variant='raised'` => `variant='contained'`
- `variant='display4'` => `variant='h1'`
- `variant='display3'` => `variant='h2'`
- `variant='display2'` => `variant='h3'`
- `variant='display1'` => `variant='h4'`
- `variant='headline'` => `variant='h5'`
- `variant='title'` => `variant='h6'`
- `variant='subheading'` => `variant='subtitle1'`
- `variant='body2'` => `variant='body1'`
- `variant='body1'` => `variant='body2'`

0.6.0 - Concern with the MUI v4.0.0

---

package.json
src/core/Button.tsx
src/docz/Button.mdx

Opacity when button is with the `selected` prop

0.6.3 - Button selected

---

package.json
src/core/Advertise.tsx
src/core/Avatar.tsx
src/core/Button.tsx
src/core/Card.tsx
src/core/Line.tsx
src/core/ListItem.tsx
src/core/Node.tsx
src/core/Progress.tsx
src/core/Sidebar.tsx
src/core/Snackbar.tsx

Name and id fields added in the follow icons/items:
- Advertise;
- Avatar;
- Button;
- Card;
- Line; 
- ListItem;
- Node;
- Progress;
- Sidebar;
- Snackbar.

0.7.6 - Name and id - Card/Avatar

---

package.json
src/core/InputBase.tsx

0.7.9 - React node

---

package.json
src/core/Sidebar.tsx

- Added name property at the sidebar component, example of use: 
`button-sidebar`

0.8.1 - Sidebar name added

---

package.json
src/core/ExpansionPanel.tsx

Smallest expand panel to best coexistence with UX team / Design

0.8.3 - Remove margin top and bottom from expanded panel 

---

package.json
src/core/Stepper.tsx

Allow change the orientation of stepper.

Orientation prop for Stepper Component.

---

src/core/Stepper.tsx
src/docz/Stepper.mdx

- icons can be used in with the stepper component by default

0.8.7 - Allowed to customize icons in Stepper component.

---

package.json
src/core/AutoComplete.tsx
src/core/ListItem.tsx

- allow the use of typography in select components;
- parallelization in autocomplete focus;

0.8.15 - Insert Typography on select component 

---

package.json
src/core/TextField.tsx

- problems with classes input on use of MaskField are solved;

0.9.2 - Problem with classes imput fixed

---

package.json
src/core/AutoComplete.tsx
src/core/Card.tsx
src/docz/AutoComplete.mdx

Breaking changes:
- `inputValue` replaced by a function called `renderInput`
- `onChange` is now required

0.12.1 - Set AutoComplete to be controlled only

---

package.json
src/core/MaskField.tsx
src/docz/MaskField.mdx

- Enable use of props to handling with money format.

0.12.7 - Props to handle with money format added

---

package.json
src/core/ListItem.tsx

- Allow possibility to use JSX elements on title prop in ListItem component.

0.12.16 - Allow use components on listItem title

---

package.json
src/core/Snackbar.tsx
src/docz/Snackbar.mdx

- Allow use of transition duration prop in snackbar for increase animation time.

0.12.18 - Add snackbar transition duration prop

---

package.json
src/core/Line.tsx
src/docz/Line.mdx

Allow use of prop for setting the width prop in Line component.

0.12.19 - Allow the width prop directly on Line component 

---

package.json
src/core/TextField.tsx

- Added helper prop to use on inputs.

0.12.20 - Allow use of helperText in TextField

---

package.json
src/core/Dialog.tsx

Added prop and possibility to add winnower on right side of dialog.

0.13.0 - Allow use a winnower on dialog

---

package.json
src/core/Snackbar.tsx
src/docz/Snackbar.mdx

- Added prop for body Snackbar doesn't jump the line and not create a white space on bottom;
- Fixed problem witth TS (command deprecated);
- Changed message on example.

0.16.1 - Added nowrap prop on Snackbar

---

package.json
src/core/Snackbar.tsx

- Space added between icon and message on snackbar.

0.16.2 - Margin left added to the snackbar messages

---

doczrc.js
package.json
src/core/Avatar.tsx
src/core/Chip.tsx
src/core/DateTime.tsx
src/core/Dialog.tsx
src/core/List.tsx
src/core/Sidebar.tsx
src/core/Snackbar.tsx
src/core/Tabs.tsx
src/core/TextField.tsx
src/docz/IconButton.mdx
src/docz/Wrapper.tsx

This PR is to solve some bugs in docz. Some table props was not working properly.
See the new deploy in https://nginformatica.github.io/flipper-ui/

0.16.4 - Fix bugs in docs presentation (docz)

---

package.json
src/core/DateTime.tsx
src/core/MaskField.tsx
src/core/Sidebar.tsx
src/core/Snackbar.tsx
src/core/TextField.tsx

This PR is to remove the unnecessary prop "classes"

0.16.5 : Remove unnecessary props

---

package.json
src/core/Tab.tsx
src/core/Tabs.tsx
yarn.lock

-Tab/Tabs changed to get the default properties from material-ui.

0.16.12 - Change Tabs component back to default

---

package.json
src/core/Drawer.tsx
src/docz/Drawer.mdx

Added options to set width and top position of the Drawer, in order to allow more customization

0.17.1 - Add option to top and width

---

package.json
src/charts/HorizontalBarChart.tsx
src/charts/LineVerticalBarChart.tsx
src/charts/ParetoLineBarChart.tsx
src/charts/SingleBarChart.tsx
src/charts/StackedBarChart.tsx
src/docz/Charts.mdx

- Added new chart to stacked data;
- Fixes on margins and size of tooltips;
- Updated elipsize function;

0.20.5 - Stacked bar chart added

---

package.json
src/charts/AreaChart.tsx
src/charts/LineAreaChart.tsx
src/charts/ParetoLineBarChart.tsx
src/docz/Charts.mdx

- Changed the charts labels to take the prop size;
- Bettering the axis ticks.

0.20.6 - Improving label text size

---

package.json
src/charts/LineAreaChart.tsx
src/charts/LineVerticalBarChart.tsx
src/charts/ParetoLineBarChart.tsx
src/charts/StackedBarChart.tsx
src/charts/style.ts
src/docz/Charts.mdx

- Added more tips fields on charts;
- Moved and created legend on some charts;
- Added function to convert data to triple tuples; 
- Improves on data visualization.

0.21.4 - Improves in charts components

---

package.json
src/charts/AreaChart.tsx
src/charts/LineAreaChart.tsx
src/docz/Charts.mdx

- Allowed margin custom values in AreaChart and LineAreaChart;
- Remove domain default value on LineAreaChart;
- Change example.

0.21.8 - Allow margin custom values on Area/LineArea Charts. 

---

package.json
src/core/Button.tsx
src/core/IconButton.tsx

- Change the type of the onClick on IconButton and Button components;
- Moved props on Button component to take the props autocomplete.

0.21.9 - Changed type of onClick in IconButton, fix on Button component props. 

---

package.json
src/core/Button.tsx

- Allowed the use of disableTouchRipple on Button component.

0.21.10- Button disableTouchRipple prop allowed

---

package.json
src/core/TableCell.tsx
src/core/TableHead.tsx
src/docz/Table.mdx

- Allowing the option to sort the row values in tables.

0.21.11 - Allow sort button prop to tables

---

package.json
src/core/TableCell.tsx
src/core/TableHead.tsx

- Now is possible to control the column that's will be sorted.

0.21.12 - Added state control by name to TableCell component

---

package.json
src/core/ListItem.tsx

- Remove the `component` prop that cause problem on `ListItem` component.

0.21.17 - Remove component prop on typographyProps

---

package.json
src/core/EditableTable.tsx
src/docz/EditableTable.mdx

- Changed to the "default export" the `EditableTable` component export

- Fixing wrong Editable Table export

---

package.json
src/core/EditableTable.tsx

- Added hook to watch the datastage is updated;
- Added the correct types to TCounterColumn type;
- Removed sort by Date on table update.

0.22.4 - Added the usePrevious to watch the state changes

---

package.json
src/core/EditableTable.tsx
src/docz/EditableTable.mdx

- Removed the default functions (add, remove and update data);
- Added properties to not render pagination and toolbar components when is not necessary; 
- Removed pointer cursor on hovering.

0.22.6 - Allowing the not render of Pagination and Toolbar default components 

---

package.json
src/core/EditableTable.tsx
src/docz/EditableTable.mdx

- Changed the editable table header toolbar to take the flipper-ui pattern. 
- General fixes (fixed wrong characters, added title on component) on `EditableTable.mdx` example.

0.22.7 - Changing the editable table add button according to the library pattern

---

package.json
src/core/EditableTable.tsx
src/docz/EditableTable.mdx

- Overwriting the `Toolbar` internal component to not render the edit/ remove icons/actions.

0.22.8 - Fixed the problem with the  toolbar actions in editable table 

---

package.json
src/core/EditableTable.tsx
src/docz/EditableTable.mdx

- Added name to inputs and buttons inside the `EditableTable`component;
- Added `fontWeight` style to text inside `AddRow`.

0.22.9 - Added name/id to editable table components

---

.vscode/settings.json
package.json
src/core/EditableTable.tsx
src/docz/EditableTable.mdx

- Allowed passing of props to render the autocomplete at `Editable Table` component;
- Added example of use of autocomplete at editable table.

0.22.10 - Allowed the autocomplete at Editable Table component

---

package.json
src/core/EditableTable.tsx
src/docz/EditableTable.mdx

###Fixes:
- Passing the correct class name to overwrite the display prop.

0.22.13 - Fix the pagination div position

---

package.json
src/docz/lab/AutocompleteNew.mdx
src/lab/Autocomplete.tsx
src/lab/AutocompleteNew.tsx
src/lab/index.ts
yarn.lock

New autocomplete

---

package.json
src/lab/AutocompleteNew.tsx

0.22.16 - Add new Autocomplete component

---

package.json
yarn.lock

- Update all the `@babel` dependencies to fix the build problem on github actions.

0.22.20 - Update @babel dependencies

---

doczrc.js
package.json
src/docz/Advertise.mdx
src/docz/README.md

- Remove base path;
- Add hashRouter;
- Fix Advertise path.

0.22.22 - Remove html errors on README.md, remove base path

---

package.json
src/core/ExpansionPanel.tsx
src/core/TextField.tsx
src/docz/ExpansionPanel.mdx
src/docz/TextField.mdx

- Added button in the `TextField` component that receives a help function.
- Added button in the `ExpansionPanel` component that receives a help function;
- In some places that use the `TextField`, it's necessary to pass the `fullWidth` prop to current thex field fill all the space;

0.24.2 - Add helper option on the `TextField` and `ExpansionPanel` components;

---

.eslintrc.json
package.json
src/core/EditableTable.tsx
src/docz/EditableTable.mdx
yarn.lock

- Updated the `material-table` dependency to the last version;
- Changes on data add/update of the Editable Table in order to keep the row opened if input errors happens.
- Added more use examples of EditableTable component;

0.24.9 - EditableTable component improvements

---

package.json
src/core/TextField.tsx
src/stories/TextField.stories.tsx

https://user-images.githubusercontent.com/43145168/153036647-c0e03fdc-7f0b-4f36-b34d-63dde20b43cb.mp4

0.25.2 - TextField Select with clear

---

package.json
src/core/PinInput.tsx
src/index.ts
src/stories/PinInput.stories.tsx

0.25.3 - Create Pin Input component

---

package.json
src/core/PinInput.tsx
src/stories/PinInput.stories.tsx

Expose Material-UI  props and inproved component code

0.25.4 - Update Pin Input component

---

package.json
src/core/TextField.tsx

Expose onPaste prop on TextField

0.25.5 - Expose onPaste prop on TextField

---

package.json
src/core/PinInput.tsx

Fixed bug were 0 (zero) weren't being displayed on Pin Input

0.25.6 - Fix PinInput - Zero Character

---

package.json
src/core/DataTable/Rows.tsx

0.25.7 - Add prop name to DateTime

---

package.json
src/core/DataTable/DataTablePaginationActions.tsx

Fix Datatable style bug in datepick and components

0.25.8:  Fix Datatable style bug in datepick and components

---

package.json
src/core/Chapter.tsx
src/stories/Chapter.stories.tsx

0.25.9: Feat - Create chapter component

---

package.json
src/index.ts

0.25.10: Fix - Export new chapter component

---

cypress/integration/Node.feature
cypress/integration/Tree.feature
cypress/integration/common/When.cy.tsx
cypress/support/utils/generators/fakes.tsx
package.json

refactor(cypress): change generate algorithm to fix inconsistency

Node and Tree unit tests are now consistent

---

cypress/integration/ExpansionPanel.feature
cypress/integration/common/Given.cy.tsx
cypress/integration/common/Then.cy.tsx
cypress/integration/common/When.cy.tsx
cypress/support/factories/expansion-panel.tsx
cypress/support/types-interfaces-enums.ts
cypress/support/utils/generators/expansion-panel-props.tsx
package.json
src/core/ExpansionPanel.tsx
src/core/TextField.tsx
src/core/types.ts
src/stories/ExpansionPanel.stories.tsx

feat(ExpansionPanel): editable variant

---

cypress/integration/Checkbox.feature
package.json
src/core/Checkbox.tsx

feat(Checkbox): ensure checkbox can spread props when using switch variant

feat(Checkbox): ensure checkbox can spread props when using switch variant

---

package.json
src/core/PinInput.tsx

Fix invalid validation when user paste token with spaces

fix(pin-input): trim input on paste

---

package.json
src/core/data-display/table/table-row.tsx
src/core/inputs/radio-group/index.tsx

Add export to interfaces to use it on Hermes Frontend.

fix: add export to interfaces

---

package.json
src/core/inputs/text-field/index.tsx
src/core/inputs/text-field/text-field.spec.tsx
src/core/inputs/text-field/text-field.stories.tsx
src/test/mocks/text-field-mock.tsx

feat: add input characters counter

feat: add input characters counter

---

src/core/inputs/text-field/index.tsx

fix: input props type

---

src/core/inputs/text-field/index.tsx

- fix: remove navigator tooltip

fix: remove navigator tooltip

---

package.json

fix: release version

---

package.json
src/core/feedback/dialog/dialog.stories.tsx
src/core/feedback/dialog/index.tsx
src/core/inputs/date-time/__snapshots__/date-time.spec.tsx.snap

- fix dialog when scroll is set to 'paper;

fix: dialog scroll

---

package.json
src/core/feedback/dialog/index.tsx

fix: dialog content
