nginformatica/flipper-ui

package.json, src/core/Checkbox.tsx
Allow uses ReactNode in checkbox's label.
=> 0.7.14 - Allow use ReactNode in checkbox's label. 

package.json, src/core/Button.tsx
Target allowed for buttons, it's could be necessary for point to external address.
=> 0.7.15 - Allow target (optional) use in the Button component 

package.json, src/core/Stepper.tsx
Add type JSX.Element to step label for allow the use of other elements as label.
=> 0.8.9 - Add type JSX.Element to step label

package.json, src/core/MaskField.tsx, src/docz/MaskField.mdx, yarn.lock
- Now is possible use number masks in flipper-ui, format prop is required for use this component.  
- Although react-number-format allow use of additional props, shows problem with some props like have been do this actually on flipper-ui. (e.g. errors treatment)
=> 0.9.0 - Insert MaskField 

package.json, src/core/AutoComplete.tsx, src/docz/AutoComplete.mdx, yarn.lock
Breaking changes:
- prop `data` renamed to `suggestions`
New features:
- `style`: Lets you set the style of the parent of the input field
- `caseSensitive`: Lets you set whether the search will be case-sensitive
=> 0.12.0 - AutoComplete field without Downshift

package.json, yarn.lock
=> 0.16.3 - Bumb typescript to 3.5.1 and @material-ui/pickers to 3.2.3

package.json, src/core/RadioGroup.tsx
- Added `row` prop that allows us to set RadioGroup orientation to horizontal
- Added `spacing` prop with two options: `default` and `equal`
- `default` spacing:
- `equal` spacing:
=> 0.16.6 - Add row option to RadioGroup

package.json, src/core/DateTime.tsx, src/docz/DateTime.mdx, yarn.lock
Added more examples for DateTime and an emphasis about locales was made in the component description (Docz)
=> 0.19.0 - Remove imports of locales (date-fns)

package.json, src/core/TextField.tsx, src/docz/TextField.mdx
=> 0.20.4 - Fix padding of TextField select

package.json, src/core/Tab.tsx
- Allowing the use of `disableRipper` on `Tab` component.
=> 0.21.16 - Enable disableRipper prop

package.json, src/core/EditableTable.tsx, src/docz/EditableTable.mdx
- Allowed the use of `noRowsExpand` prop to don't show the select number of rows menu.
- Added a fixed size to the editable table body.
=> 0.22.10 - Created prop to omit the number of rows at editable table select menu

package.json, src/core/EditableTable.tsx
###Fix:
- Try another way to position the pagination component at table footer.
=> 0.22.14 - Fix the pagination components position at Editable Table

package.json, src/core/EditableTable.tsx, yarn.lock
- Fixed the pagination tooltips when the `noExpandRows` is passed to the `EditableTable` component;
- Added verification to put a fixed size only when `noExpandRows` is active;
- Updated the Material-Table dependency to the last stable version.
=> 0.22.15 - Fixed the pagination tooltips when the noExpandRows prop is true

package.json, src/core/EditableTable.tsx, src/docz/EditableTable.mdx, yarn.lock
- Was enabled the use of `MaskField` inside `EditableTable`;
- Allowed the onRowClick prop on `EditableTable`; 
- Removed unecessary props;
- Updated the  react-number-format and material-table dependency.
=> 0.22.18 - Add MaskField in EditableTable

package.json, src/core/EditableTable.tsx, yarn.lock
- Passed props to render the number values only as Integers in `EditableTable` component.
=> 0.22.19 - MaskField on EditableTable component is accepting only integers

README.md, doczrc.js, package.json, src/docz/Advertise.mdx, src/docz/Box.mdx, src/docz/Header.mdx, src/docz/Index.mdx, src/docz/Sidebar.mdx, src/docz/Stepper.mdx, src/docz/Tabs.mdx, src/docz/Tooltip.mdx
- Removed, for now, the Props component at mdx examples; 
- Created index for docz-vercel; 
- Removed hashRouter from the `doczrc.js` configs.
=> 0.22.23 - Removed, temporarily, Props from docz mdx

package.json, src/core/EditableTable.tsx, src/docz/EditableTable.mdx
- Added `disableAddHeader` prop, to disable the Add button on table's header. 
- Allowed the `errors` prop that receive a list of errors when the values of fields are changed.
=> 0.23.1 - Allowed the disable add button prop on Editable Table component

package.json, src/core/ChipField.tsx, yarn.lock
- Use the correct type functions for `onDelete` and `OnAdd` props;
- Use 4 spaces identation instead 2;
- Changed the style pattern of `ChipField` to take the `TextField` component's sytle.
=> 0.24.1 - Fixing ChipField props types

package.json, src/core/TextField.tsx
- pass the `fullWidth` prop in `TextField` instead spread the values.
=> 0.24.4 - Use the fullWidth prop on the Text Field component

package.json, src/core/Checkbox.tsx, src/core/ExpansionPanel.tsx, src/core/TextField.tsx, src/docz/Checkbox.mdx, src/docz/ExpansionPanel.mdx
- Added the default helper button option on the `CheckBox` component (switch mode also). It's necessary to pass the `onHelperClick` as prop in the `CheckBox` for render it correctly;
- Added option that allow the positioning of the helper button on the `ExpansionPanel` component;
- Added some examples for these two cases above. 
- Created the `HelperButton` component that can be used on all the fields in the future.  For now, it's used only on `TextField`, `CheckBox` and `ExpansionPanel`.
=> 0.24.5 - Added helper button on the CheckBox component

package.json, src/core/Checkbox.tsx, src/core/ExpansionPanel.tsx
- Add `ExpansionPanelHeaderWrapper` on the `ExpansionPanel` component instead use the generic wrapper;
- Pass the default props to the `CheckBox` components.
=> 0.24.7 - Create a specific helper warper for the ExpansionPanel component

package.json, src/core/Checkbox.tsx, src/docz/Checkbox.mdx
- Pass only id and name instead all the props to  `Switch` and `CheckBox` material-ui components.
=> 0.24.8 - Remove the props spread to Switch and `CheckBox` components

package.json, src/colors.ts, src/core/EditableTable.tsx, src/lib/localization.ts
- Aligned the `MaskField` of the `EditableTable` component on the right with the column title.
- Moved the localization object to a function `getLocalization`, created a file for that function on the new lib directory.
=> 0.24.10 - Positioning the EditableTable's MaskField always on the right

package.json, src/core/EditableTable.tsx
- Altered the props `onRowAddCancelled` and `onRowUpdateCancelled` to optional in order to avoid errors/warns.
=> 0.24.11 - Changed to optional the row edit cancel functions on EditableTable component

package.json, src/core/EditableTable.tsx
- Pass a default `fontFamily` (Roboto) as `rowStyle` prop to `EditableTable` to avoid fonts inheritance issues.
https://github.com/mbrn/material-table/issues/2080
=> 0.24.12 - Fixed default font on rowStyle in EditableTable component

package.json, src/core/EditableTable.tsx, src/docz/EditableTable.mdx
- Used the `material-table` error handling beside the custom error handler on numeric and date fields;
- To use it, it's necessary add the field `validate` on the `columns` object and not pass the errors array to `EditableTable`. 
- Added a more specific example using that new approach.
=> 0.24.13 - Improved error handling on EditableTable component 

package.json, src/core/Select.tsx, src/stories/Select.stories.tsx
Improved select component
`hasClear` and `onClear` can be passed as props to be able do clear select value
=> 0.25.1 - Select with clear

package.json, src/core/inputs/select/index.tsx, src/core/inputs/select/select.spec.tsx, src/core/inputs/select/select.stories.tsx, src/test/mocks/select-mock.tsx
Algumas implementações do componente no produto utilizam mais elementos do event do que somente seu value, entao foi necessário voltar a utilizar o event completo como parâmetro no callback
=> hotfix(select): onChange props with event instead of its target value

.babelrc.js, package.json, yarn.lock
Com a atualização do Flipper o projeto possui aliases que auxiliam o desenvolvimento, esses aliases estavam sendo transpilados e causando problemas na importação, configurado o module resolver no babel para o mesmo converter esses imports
=> chore(babel): configure module resolver to convert project aliases in normal imports and avoid path errors

package.json, src/core/feedback/dialog/dialog.spec.tsx, src/core/feedback/dialog/index.tsx
Por default, a propriedade "title" é utilizada pelos navegadores para renderizar um tooltip da tag. 
Essa propriedade que estava presente para testes E2E no Dialog fazia com que o navegador renderizasse um tooltip escrito "dialog-paper".
Como essa propriedade é mais utilizada para acessibilidade, adicionou-se uma prop no Dialog chamada "aria-title", que recebe o titulo usado nos testes, se não for presente, não adiciona a propriedade "title" no Paper, evitando a renderização do tooltip.
=> fix(Dialog): conditionally render title prop

package.json, src/core/inputs/text-field/index.tsx, src/core/inputs/text-field/text-field.spec.tsx, src/core/inputs/text-field/text-field.stories.tsx, src/test/mocks/text-field-options-mock.tsx
Foi implementadada uma nova forma de reenderizer o select.
Agora utilizamos a propriedade options para reenderizar um select de opções ou optamos por utilizar o input normal de texto.
Observando o comportamento anterior do select continua a funcionar normal.
Foram também adicionados novos testes,  para atender o novo comportamento do componente.
=> feat: add the select by options

package.json, src/core/inputs/button/button.spec.tsx, src/core/inputs/button/index.tsx
Foram alterados os valores de dashed e outlined para corrigir a ausência de borda em alguns botões.
É possivel que seja necessário o ajuste em alguns lugares onde está sendo utilizado o componente e tem váriação dos valores dashed e outlined.
=> fix: the problem with the border style

package.json, src/core/inputs/text-field/index.tsx
=> fix: help icon color

package.json, src/core/data-display/data-table/rows.tsx, src/core/inputs/auto-complete/__snapshots__/auto-complete.spec.tsx.snap, src/core/inputs/date-time/__snapshots__/date-time.spec.tsx.snap, src/core/inputs/mask-field/__snapshots__/mask-field.spec.tsx.snap, src/core/inputs/text-field/__snapshots__/text-field.spec.tsx.snap, src/core/inputs/text-field/index.tsx, src/core/inputs/text-field/styles.ts, src/experimental/auto-complete-lab/autocomplete-lab.stories.tsx
- chore: add key to table row;
- fix: adjust textfield character count position;
=> fix/adjust textfield character count position;
